# Relevant Libraries

In [5]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression as LR

# Load the Data

In [6]:
data = pd.read_csv(r"C:\Users\Tauseef\Deep_Learning\2-Regression\dataset\GPAvsETEA_.csv")

In [7]:
data.head()

ETEA   GPA  rand
0  428.50  2.40     3
1  416.00  2.52     2
2  440.00  2.54     3
3  421.25  2.74     2
4  423.25  2.83     1

# Multiple Linear Regression

###    Define dependent and independent variable

In [8]:
x = data[['ETEA','rand']]
y = data['GPA']

# Regression ITSELF

In [9]:
reg = LR()
reg.fit(x,y)

LinearRegression()

In [10]:
reg.coef_

array([ 0.00659305, -0.02094818])

In [11]:
reg.intercept_

0.33013907260363107

### Calculating R-Squared

In [12]:
reg.score(x,y)

0.41057882341634555

### Formula for Adjusted R^2 
#### Adjusted R Squared = 1 – [(1 – R2) * (n – 1) / (n – k – 1)]

In [13]:
x.shape

(84, 2)

In [14]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39602521411798375

In [25]:
from  sklearn.feature_selection import f_regression

In [26]:
f_regression(x,y)

(array([56.04804786,  0.73844876]), array([7.19951844e-11, 3.92663490e-01]))

In [27]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 3.92663490e-01])

In [28]:
p_values.round(3)

array([0.   , 0.393])

## Summary Table

In [22]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0     ETEA
1     rand

In [23]:
reg_summary['coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [24]:
reg_summary

Features  coefficients  p-values
0     ETEA      0.006593     0.000
1     rand     -0.020948     0.393