# Relevant Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression as LR

# Load the Data

In [2]:
data = pd.read_csv(r"C:\Users\Tauseef\Deep_Learning\2-Regression\dataset\GPAvsETEA_.csv")

In [3]:
data.head()

ETEA   GPA  rand
0  428.50  2.40     3
1  416.00  2.52     2
2  440.00  2.54     3
3  421.25  2.74     2
4  423.25  2.83     1

# Multiple Linear Regression

###    Define dependent and independent variable

In [4]:
x = data[['ETEA','rand']]
y = data['GPA']

# Standardization

In [7]:
from sklearn.preprocessing import StandardScaler as SS

In [8]:
scaler = SS()

In [9]:
scaler.fit(x)

StandardScaler()

In [13]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288,  1.17335776],
       [-1.74458431,  0.02728739],
       [-0.82067757,  1.17335776],
       [-1.54247971,  0.02728739],
       [-1.46548748, -1.11878298],
       [-1.68684014,  1.17335776],
       [-0.78218146,  1.17335776],
       [-0.78218146, -1.11878298],
       [-0.51270866,  1.17335776],
       [ 0.04548499,  1.17335776],
       [-1.06127829,  1.17335776],
       [-0.67631715,  1.17335776],
       [-1.06127829, -1.11878298],
       [-1.28263094, -1.11878298],
       [-0.6955652 ,  1.17335776],
       [ 0.25721362, -1.11878298],
       [-0.86879772, -1.11878298],
       [-1.64834403, -1.11878298],
       [-0.03150724, -1.11878298],
       [-0.57045283,  0.02728739],
       [-0.81105355, -1.11878298],
       [-1.18639066,  1.17335776],
       [-1.75420834,  1.17335776],
       [-1.52323165, -1.11878298],
       [ 1.23886453,  1.17335776],
       [-0.18549169, -1.11878298],
       [-0.5608288 , -1.11878298],
       [-0.23361183, -1.11878298],
       [ 1.68156984,

### Regression with scaled features

In [14]:
reg = LR()

In [15]:
reg.fit(x_scaled,y)

LinearRegression()

In [16]:
reg.coef_

array([ 0.17126539, -0.01827826])

In [17]:
reg.intercept_

3.330238095238095

## Summary Table

In [20]:
reg_summary = pd.DataFrame([['Bias'],['ETEA'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1        ETEA  0.171265
2  Rand 1,2,3 -0.018278

### Making predictions with standardize coeff ( weights)

In [22]:
new_data = pd.DataFrame(data=[[500,2],[484,1]],columns=['ETEA','rand'])
new_data

ETEA  rand
0   500     2
1   484     1

In [23]:
reg.predict(new_data)

array([88.9263786 , 86.20441056])

In [24]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[ 1.48908927,  0.02728739],
       [ 0.87315144, -1.11878298]])

In [25]:
reg.predict(new_data_scaled)

array([3.58476879, 3.50022813])